---
title: "Untitled"
output: pdf_document
date: "2026-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(car)
library(alr4)
library(leaps)
library(countrycode)


transit_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2021/2021-01-05/transit_cost.csv')

```



```{r data cleaning}

clean_transit <- transit_cost %>%
  select(c(e, country, city, start_year, end_year, rr, length, tunnel_per, tunnel, stations, year, ppp_rate, real_cost, cost_km_millions)) %>%
  filter(!is.na(e) & real_cost != 0)

clean_transit <- clean_transit %>%
  mutate(real_cost = as.numeric(real_cost)) %>%
  mutate(rr = as.factor(rr)) %>%
  filter(end_year <= 2026) %>%
  mutate(duration = as.numeric(end_year) - as.numeric(start_year))

```



```{r}

clean_transit %>%
  group_by(country) %>%
  count(sort = T)

gb <- filter(clean_transit, clean_transit$country == "UK") %>%
  mutate(country = "GB")

clean_transit<- subset(clean_transit, !e %in% c(7226, 7336, 7417))
clean_transit <- rbind(clean_transit, gb)
  

clean_transit$region <- countrycode(sourcevar = clean_transit$country,
                            origin = "iso2c",
                            destination = "region23")

df <- clean_transit %>%
  select(c(e, rr, length, stations, ppp_rate, real_cost, cost_km_millions, duration, region, year))

clean_transit %>%
  group_by(region) %>%
  summarize(mean_cost = mean(real_cost), median_cost = median(real_cost), mean_duration = mean(duration, na.rm=T), mean_length = mean(length), mean_cost_by_km = mean(cost_km_millions)) 

transit_cost[transit_cost['e'] == 8203]
```







```{r exploration}

pairs(df[, c(7, 9, 10, 12, 13, 14, 15)])

#boxplots
ggplot(df) +
  geom_boxplot(mapping = aes(y = real_cost, fill = continent))

ggplot(df) +
  geom_boxplot(mapping = aes(y = cost_km_millions, fill = continent))


#scatterplots
ggplot(df) +
  geom_point(aes(x = length, y = real_cost, colour = continent))

ggplot(df) +
  geom_point(aes(x = length, y = duration, colour = continent))

```











## Data Exploration 


### Check for correlation
```{r}
full_log <- lm(log(real_cost) ~ region + year+ length + stations+ ppp_rate+duration, data = df)
full <- lm(real_cost ~ region + year+ length + stations+ ppp_rate+duration, data = df)
summary(full)
summary(full_log)
vif(full)
plot(full) 
plot(full_log) 
hist(full_log$residuals)

table(df$region)
```

### Check for outliers

```{r}
outlierTest(full_log)
```

### Model selection 
#### apply forward, backward, and bidirection
```{r}
reg <- regsubsets(
  real_cost ~ region + year+ length + stations+ ppp_rate+duration,
  data = df,
  nbest = 1,
  nvmax = 10
)
reg_summary <- summary(reg)
bic_min_index <- which.min(reg_summary$bic)
bic_min_model <- reg_summary$which[bic_min_index, ]
cp_min_index <- which.min(reg_summary$cp)
cp_min_model <- reg_summary$which[cp_min_index, ]
bic_min_model
cp_min_model
```
BIC: Continent, year, stations 
Cp: Northern America, 


